import {
  FaWifi, FaTv, FaSnowflake, FaWineGlassAlt, FaConciergeBell, FaLock, FaCoffee,
  FaBath, FaShower, FaUmbrellaBeach, FaSwimmingPool, FaUserTie, FaUtensils,
  FaDumbbell, FaSpa, FaCar, FaTree, FaFilm, FaCouch, FaBaby, FaWater,
  FaBriefcase, FaMugHot, FaBroom, FaRegClock, FaChild,
} from "react-icons/fa";
import { MdBalcony, MdMeetingRoom, MdOutlineRoomService, MdYard, MdHotTub } from "react-icons/md";

// Maps amenity label -> icon component. Falls back to a bell.
const MAP = {
  "Free WiFi": FaWifi,
  "Smart TV": FaTv,
  "Air Conditioning": FaSnowflake,
  "Mini Bar": FaWineGlassAlt,
  "Room Service": MdOutlineRoomService,
  "In-room Safe": FaLock,
  "Coffee Machine": FaCoffee,
  "Bathtub": FaBath,
  "Bathtub for Two": MdHotTub,
  "Twin Soaking Tub": MdHotTub,
  "Deep Soaking Tub": MdHotTub,
  "Rain Shower": FaShower,
  "Outdoor Shower": FaShower,
  "Steam Shower": MdHotTub,
  "Private Balcony": MdBalcony,
  "Private Terrace": MdBalcony,
  "Grand Terrace": MdBalcony,
  "Wraparound Terrace": MdBalcony,
  "Private Lawn": MdYard,
  "Private Garden": FaTree,
  "Secret Garden": FaTree,
  "Pool Access": FaSwimmingPool,
  "Private Plunge Pool": FaSwimmingPool,
  "Private Pool": FaSwimmingPool,
  "Daily Housekeeping": FaBroom,
  "Blackout Curtains": MdMeetingRoom,
  "Workspace": FaBriefcase,
  "Smart Controls": FaTv,
  "Executive Lounge": FaUserTie,
  "Lounge Nook": FaCouch,
  "Living Lounge": FaCouch,
  "Living Area": FaCouch,
  "Grand Living Room": FaCouch,
  "Outdoor Lounge": FaUmbrellaBeach,
  "Butler on Call": FaConciergeBell,
  "Dedicated Butler": FaConciergeBell,
  "Breakfast Included": FaMugHot,
  "Nespresso Bar": FaCoffee,
  "Spa Access": FaSpa,
  "Couples Spa": FaSpa,
  "Private Spa": FaSpa,
  "Yoga Mat": FaSpa,
  "Champagne Welcome": FaWineGlassAlt,
  "Candlelit Dining": FaUtensils,
  "Private Dining": FaUtensils,
  "Dining Area": FaUtensils,
  "Private Chef on Request": FaUtensils,
  "Private Gym": FaDumbbell,
  "Home Cinema": FaFilm,
  "Limousine Transfer": FaCar,
  "Two Bathrooms": FaBath,
  "Connecting Rooms": MdMeetingRoom,
  "Two Floors": MdMeetingRoom,
  "Kids' Nook": FaChild,
  "Kids' Amenities": FaBaby,
  "Pool View": FaWater,
  "24h Service": FaRegClock,
};

export default function AmenityIcon({ name, className }) {
  const Icon = MAP[name] || FaConciergeBell;
  return <Icon className={className} aria-hidden="true" />;
}
